meta_product_name: "Matech"
meta_title: "Matech - the way to curate your creative search"
meta_description: "Smart tool to save and organize your files using tags"
meta_image: "og.jpg"                       # should exist in `app/assets/images/`
  # required for Twitter Cards
